[build]
builder = "nixpacks"
buildCommand = "nixpacks install unzip && curl -fsSL https://bun.sh/install | bash && ~/.bun/bin/bun install"

[deploy]
startCommand = "~/.bun/bin/bun run src/index.ts"
healthcheckPath = "/health"
healthcheckTimeout = 100
